language: "fr"
pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  "max_ngram": 2
  "token_pattern": "(?u)\\b\\w+\\b"
- name: "intent_classifier_tensorflow_embedding"
  "epochs": 500
path: "./models/nlu"
data: "./data/data.md"